### ISSUE TITLE
Compile error for children_iterator

### ISSUE THREAD

**Issue by lczech** [niemasd/CompactTree#3]
Under Clang 11.0.0, with warnings as errors, the code fails to compile, with this error:

```
compact_tree.h:336:17: error: definition of implicit copy assignment operator for 'children_iterator' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
                children_iterator(const children_iterator & o) : it(o.it) {}
                ^
compact_tree.h:479:23: note: in implicit copy assignment operator for 'compact_tree::children_iterator' first required here
            for(ch_it = children_begin(curr), ch_it_end = children_end(curr); std::next(ch_it) != ch_it_end; ++ch_it) {
                      ^
```

This can be fixed by not pre-declaring `ch_it`, and instead using `auto ch_it` in the loop. This also affects two more loops later on in the code.

**Comment by niemasd** [comment]
Hmm, very strange! Based on this and the other issue, it seems like there are some compiling and runtime issues with Clang specifically (I've been testing with g++). I'll investigate, and I'll try to add some automated tests in GitHub Actions to catch this type of thing. Thanks for reporting these issues!

**Comment by lczech** [comment]
Sure! From personal experience, I'd recommend to test with as many GCC and Clang versions as you can, and also Apple Clang, and other compilers on macos. They all tend to find different bugs here and there, so running them all is a good idea, and relatively easy in GitHub Actions

**Comment by niemasd** [comment]
That's a great idea! I definitely want to add those tests soon. Definitely on the roadmap!

Re: the original issue, I think it might be good for me to implement a proper copy assignment operator for those classes, just in case folks choose to use those classes in the same way I did:

https://stackoverflow.com/a/74397484/2134991

So I'll see if I can fix the original issue. Will follow up soon!

**Comment by niemasd** [comment]
Okay, I just pushed an update (https://github.com/niemasd/CompactTree/commit/2ee077a8d59c52d2924ecb45da8dfabd5026e5f6) that I *think* should hopefully fix the compile error you were originally getting. Would you be able to revert to the original usage of `ch_it` to see if it compiles now on your end with this update?

**Comment by lczech** [comment]
Yep, compiles with Clang 11 now!

**Comment by niemasd** [comment]
Awesome, thank you for confirming! 😄
