### ISSUE TITLE
Add levelorder_iterator class

### ISSUE THREAD

**Issue by niemasd** [niemasd/CompactTree#7]
Right now, the only way to run a level-order traversal is to manually implement BFS from the root using a queue: there is no clean iterator class that can just iterate over all the nodes in a level-order traversal. It would be good to add a class called `levelorder_iterator` that implements this

One key challenge is figuring out how to find the next node from the current node. One option could be to store the queue as a static variable in the `levelorder_iterator` class and have each individual `levelorder_iterator` object have access to it, but that could pose challenges if there are multiple independent `levelorder_iterator` objects at the same time

Maybe I could have an `std::vector<std::queue<CT_NODE_T>>` that stores *all* queues or *all* current level-order traversals that I keep appending to each time `begin()` is called? Or maybe an `std::unordered_map<std::queue<CT_NODE_T>>` instead so that I can also completely destroy the `std::queue` associated with a specific level-order traversal the moment the queue becomes empty?

**Comment by niemasd** [comment]
Actually, maybe it'll be better to just have the `std::queue` be a member variable *within* the `levelorder_iterator` class. That way, if you copy a `levelorder_iterator` object, you'll still have a valid level-order traversal ready to go (at the cost of a memory copy operation), but pre-increment shouldn't incur any additional runtime cost

**Comment by lczech** [comment]
Yep, as said in #6, static won't work here, but a normal member variable in the iterator class works fine.

**Comment by niemasd** [comment]
Yeah, good thinking! I think I'll go ahead and do that. I can just add a blurb to the cookbook emphasizing to the user that they should try to avoid copying `levelorder_iterator` objects and try to use pre-increment when possible to avoid the time/memory overhead of copying the entire BFS queue

**Comment by lczech** [comment]
Iterators are usually only ever copied in the beginning, to set up the for loop, but rarely during the loop body. If so, yes, that could be seen as a thing that users should avoid, but I think any good code would take the iterator by reference anyway. Alternatively, the queue can be kept in a `std::shared_ptr` to avoid that - but that of course would mean that no intermediate levelorder state can be kept if needed (which probably is not a use case anyway).

As for the pre- vs post-order, there is a mechanism for that in C++, via `operator++` vs `operator++(int)`, see https://en.cppreference.com/w/cpp/language/operator_incdec

**Comment by niemasd** [comment]
> Iterators are usually only ever copied in the beginning, to set up the for loop, but rarely during the loop body.

Hmm, I'm not sure this is the case if the user performs a post-increment on an iterator. To my knowledge, a post-increment operator implementation must create a copy of the iterator object at some point (or at least I'm not sure how to avoid creating a copy of the calling iterator object during a post-increment). For example, in the following loop, I *believe* the statement `it++` must be making a copy of `it` that it's using within the dereference operator in the print statement:

```cpp
auto it = my_container.begin();
while(it != my_container.end()) {
    std::cout << *(it++) << std::endl;
}
```

I could be mistaken, but I believe that, regardless of implementation details, `it++` is modifying the internal state of `it` in some way to move it to the next element but then returning a copy of `it` that was made *prior* to those modifications to the internal state (i.e., a copy of how `it` looked like before the increment), and the dereference operator is dereferencing that copy

Of course, this unnecessary copying via post-increment operator can be avoided easily by not dereferencing the iterator object in the same exact statement in which it's being incremented, but it is technically a valid use-case that someone might want to do for some reason

> As for the pre- vs post-order, there is a mechanism for that in C++, via operator++ vs operator++(int), see https://en.cppreference.com/w/cpp/language/operator_incdec

Thanks for sharing! I'm already familiar with how to implement pre-increment vs. post-increment in C++ iterators, as I do so already for the existing iterator classes within CompactTree, but this is a useful reference to have handy!

https://github.com/niemasd/CompactTree/blob/c9a7593c738ce423f768f99b0f51630a67c9df74/compact_tree.h#L258-L259

https://github.com/niemasd/CompactTree/blob/c9a7593c738ce423f768f99b0f51630a67c9df74/compact_tree.h#L287-L288

https://github.com/niemasd/CompactTree/blob/c9a7593c738ce423f768f99b0f51630a67c9df74/compact_tree.h#L316-L317

https://github.com/niemasd/CompactTree/blob/c9a7593c738ce423f768f99b0f51630a67c9df74/compact_tree.h#L346-L347

**Comment by lczech** [comment]
Ah right, thanks for the info! If you do not provide a post increment operator, the user will not be able to write `it++`, so that way you could disallow the expensive copy :-)

**Comment by niemasd** [comment]
True! For now, I think I'll include the post-increment operator just in case the user wants to use it, but I'll warn them about the queue copy. I just pushed an update (https://github.com/niemasd/CompactTree/commit/85c388c7447d3ebb4d88ac2486e587ffb27bd5a1) that added a `levelorder_iterator` class (and updated all documentation accordingly) and another update (https://github.com/niemasd/CompactTree/commit/e7ccb9b0d4fae1c02ec1e923acc99fd9c76fb4bd) that adds a warning about the extra time and memory of the copy constructor and post-increment operator

Thank you so much for this excellent discussion! This was a great idea, and I just needed someone to give me a bit of a push in the right direction to get it implemented 😄
